name: Deploy to EC2

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      triggerReason:
        description: "Why are you manually deploying?"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/algoduck_judge || git clone https://github.com/jwelyl/algoduck_judge.git algoduck_judge && cd algoduck_judge
            git pull origin develop

            # Copy .env.template to .env and replace TESTCASE_BASE_PATH with GitHub secret
            cp .env.template .env
            sed -i "s|^TESTCASE_BASE_PATH=.*|TESTCASE_BASE_PATH=${{ secrets.TESTCASE_BASE_PATH }}|" .env

            docker stop judge-server || true && docker rm judge-server || true
            docker build -t judge-server .
            docker run -d -p 8000:8000 --env-file .env --name judge-server judge-server
          EOF
